title: Star HPC
lang: en
description: Star HPC – at Hofstra University
homeurl: https://starhpc.hofstra.io

#debug: true

#theme: jekyll-rtd-theme

# needed to build via GH actions
remote_theme: StarHPC/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - quickstart/quick_long_start.md
  - quickstart/access-policies.md

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
